export interface ScreenedPool {
	pool: string;
	name: string;
	baseSymbol: string;
	baseMint: string | null;
	baseIcon: string | null;
	quoteSymbol: string;
	quoteIcon: string | null;
	tvl: number;
	activeTvl: number;
	mcap: number;
	holders: number;
	organicScore: number;
	quoteOrganic: number;
	feeActiveTvlRatio: number;
	volatility: number;
	binStep: number;
	baseFeePct: number;
	volume: number;
	fee: number;
	activePositions: number;
	openPositions: number;
	tokenAgeHours: number | null;
	score: number;
	price: number;
	priceChangePct: number | null;
	volumeChangePct: number | null;
	fromAthPct: number | null;
	tokenXAddress: string;
	rugScore?: number | null;
	priceSeries?: number[] | null;
	bundlePct?: number | null;
	top10Pct?: number | null;
	botHoldersPct?: number | null;
	globalFeesSol?: number | null;
	isRugpull?: boolean | null;
	isWash?: boolean | null;
	devSoldAll?: boolean | null;
	dexScreenerPaid?: boolean | null;
	priceVsAthPct?: number | null;
	poolAgeHours: number | null;
	swapCount: number;
	uniqueTraders: number;
	priceTrend: string | null;
	lpLockedPct?: number | null;
}
